### ISSUE TITLE
some questions about ControlRoom and OperationInRoom

### ISSUE THREAD

**Issue by Gusabary** [SailGame/Core#9]
+ what does the `custom` field in `ControlRoomRet` stand for
+ not clear about the `Ready` enumeration: in which condition should the `ready` field in `RoomOperation` be set to `UNSET`, `READY` or `CANCEL`? I assume 
  + when user clicks something like ready button, client side will send an `OperationInRoomArgs` message with `ready=READY`
  + when user cancels to be ready, `ready=CANCEL` will be sent
  + and when the room owner clear room settings, `ready=UNSET` will be sent

**Comment by Veiasai** [comment]
1. if the client sends wrong/unknown settings by ControlRoomArgs,  core can't catch this thing, so, the custom in ret is for provider to notify client the error.
2. unset is the default value, means : don't change ready state. otherwise, core will change the state. This is a tricky topic, as proto3 doesn't have optional field, I am not sure what's the best practice, use a UNSET default value? or use oneof() ?

**Comment by Gusabary** [comment]
I suppose the principle is "if the `custom` is set while `ready` is unset, don't change ready state", so perhaps you can use, like,  `has_ready()` or `RoomOperation_case() == RoomOperationCase::kReady` to check whether `ready` is set or not.

**Comment by Veiasai** [comment]
previously I used bool Ready and found out there is no has_ready()...even it is under oneof()
yeah, after I change it to enum,  it should be useless to maintain a UNSET.

edit: fuxk, there is no has_ready() though we use enum

**Comment by Gusabary** [comment]
yep, curious why there is just a internal_has_ready()
